### PR TITLE
 Make config file a required flag

### PR DESCRIPTION
**Pull request by ironcladlou**
Introduce Cobra for flag handling, and make config a required flag.

### CODE REVIEW

**Comment by ironcladlou** [comment]
Will update the app template next.

**Comment by twiest** [comment]
/lgtm

Will wait for Joel's response before I merge this.

**Comment by ironcladlou** [comment]
I need this one merged ASAP so I can move on to adding https support. I've been testing a build of this in a GCE cluster to get the installer work done and am pretty confident in the changes.

**Comment by ironcladlou** [comment]
The deployment template in this repo still needs work, but I don't want to mess with it just yet since I'm still iterating on the "real" manifest which lives in openshift-ansible. We'll need to figure out a better way of maintaining another one here.

**Comment by ironcladlou** [comment]
Actually I can use the oauth proxy in front

**Comment by ironcladlou** [comment]
Actually I need to ask Frederic about https in the morning 😁

**Comment by twiest** [comment]
Merging per ASAP comment.

If @joelsmith needs something changed, we'll do it in a follow up PR.

**Pull request merged**
