### PR TITLE
create container.yaml for odcs multi-arch builds

### PR DESCRIPTION
**Pull request by jeffdyoung**
create container.yaml for odcs multi-arch builds
@dorzel @adammhaile Please review.

### CODE REVIEW

**Comment by dorzel** [comment]
+1

**Comment by jeffdyoung** [comment]
@derekwaynecarr @twiest  Ok to merge? We need to get this in so @adammhaile can enable ppc64le builds for OCP.

**Comment by twiest** [comment]
@jeffdyoung I don't know who owns this repo now, so I'll defer to @derekwaynecarr.

**Comment by jeffdyoung** [comment]
Dropping this. We won't be doing odcs builds in the near future. Thanks!

**Pull request closed without merging**
